Upgraded to SAMRAI3.11.2

diff --git a/base/SAMRAI/SAMRAI/Makefile.in b/base/SAMRAI/SAMRAI/Makefile.in
--- a/base/SAMRAI/SAMRAI/Makefile.in
+++ b/base/SAMRAI/SAMRAI/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for the entire SAMRAI distribution 
 ##
 #########################################################################
@@ -18,8 +18,8 @@ OBJECT  = .
 include ./config/Makefile.config
 
 INCLUDE_SAM = @top_srcdir@/source/SAMRAI
-INSTALL	    = sh @srcdir@/config/install-sh
-INSTDIR	    = @INSTDIR@
+INSTALL     = @INSTALL@
+INSTDIR     = @INSTDIR@
 
 #
 # GNUMake script to reverse strings.  This is recursive.
@@ -60,7 +60,7 @@ cleantest:
 	cd source/test && $(MAKE) clean
 
 checkclean:
-	cd source/test && $(MAKE) clean
+	cd source/test && $(MAKE) checkclean
 
 # Build temporary files containing list of object files for each
 # library.
@@ -141,42 +141,43 @@ install: library tools
 	$(INSTALL) -d -m 755 $(INSTDIR)/bin
 	$(INSTALL) -d -m 755 $(INSTDIR)/include
 	$(INSTALL) -d -m 755 $(INSTDIR)/include/SAMRAI
-	$(INSTALL) -c -m 644 COPYRIGHT $(INSTDIR)
-	$(INSTALL) -c -m 644 config.status $(INSTDIR)/config
-	$(INSTALL) -c -m 644 config/Makefile.config $(INSTDIR)/config
+	$(INSTALL) -p -c -m 644 COPYRIGHT $(INSTDIR)
+	$(INSTALL) -p -c -m 644 COPYING.LESSER $(INSTDIR)
+	$(INSTALL) -p -c -m 644 config.status $(INSTDIR)/config
+	$(INSTALL) -p -c -m 644 config/Makefile.config $(INSTDIR)/config
 	cat config/Makefile.config.install >> $(INSTDIR)/config/Makefile.config 
-	$(INSTALL) -c -m 644 include/SAMRAI/SAMRAI_config.h $(INSTDIR)/include/SAMRAI/
+	$(INSTALL) -p -c -m 644 include/SAMRAI/SAMRAI_config.h $(INSTDIR)/include/SAMRAI/
 	@for i in $(SAMRAI_LIBRARIES); \
 	do \
-           $(INSTALL) -d -m 755 $(INSTDIR)/include/SAMRAI/$$i;                    \
-           for f in $(INCLUDE_SAM)/$$i/*.[hICi]; do                               \
-              $(INSTALL) -c -m 644 $$f $(INSTDIR)/include/SAMRAI/$$i;             \
-           done;                                                                  \
-           if test -d $(INCLUDE_SAM)/$$i/fortran; then                            \
-              for f in $(INCLUDE_SAM)/$$i/fortran/*.[i]; do		          \
-		if test -f $$f; then                                              \
-	           if ! test -d $(INSTDIR)/include/SAMRAI/$$i/fortran; then       \
-		      $(INSTALL) -d -m 755 $(INSTDIR)/include/SAMRAI/$$i/fortran; \
-	           fi;                                                            \
-	           $(INSTALL) -c -m 644 $$f $(INSTDIR)/include/SAMRAI/$$i/fortran;\
-		fi                                                                \
-	     done;                                                                \
-	   fi                                                           	  \
+	   $(INSTALL) -p -d -m 755 $(INSTDIR)/include/SAMRAI/$$i; \
+	   for f in $(INCLUDE_SAM)/$$i/*.[hICi]; do \
+	      $(INSTALL) -p -c -m 644 $$f $(INSTDIR)/include/SAMRAI/$$i; \
+	   done; \
+	   if test -d $(INCLUDE_SAM)/$$i/fortran; then \
+	      for f in $(INCLUDE_SAM)/$$i/fortran/*.[i]; do \
+		 if test -f $$f; then \
+		    if ! test -d $(INSTDIR)/include/SAMRAI/$$i/fortran; then \
+		       $(INSTALL) -d -m 755 $(INSTDIR)/include/SAMRAI/$$i/fortran; \
+		    fi; \
+		    $(INSTALL) -p -c -m 644 $$f $(INSTDIR)/include/SAMRAI/$$i/fortran; \
+		 fi \
+	      done; \
+	   fi \
 	done
-	@if test -f lib/libSAMRAI_tbox.a; then                           \
-		for i in lib/libSAMRAI*.a; do				\
-		   $(INSTALL) -c -m 644 $$i $(INSTDIR)/lib;             \
-		done                                                    \
-	fi 
-	@if test -f lib/libSAMRAI_tbox.so; then                          \
-		for i in lib/libSAMRAI*.so; do				\
-		   $(INSTALL) -c -m 644 $$i $(INSTDIR)/lib;             \
-		done                                                    \
+	@if test -f lib/libSAMRAI_tbox.a; then \
+	   for i in lib/libSAMRAI*.a; do \
+	      $(INSTALL) -p -c -m 644 $$i $(INSTDIR)/lib; \
+	   done \
 	fi
-	@if test -f bin/restart-redistribute; then                       \
-		for i in bin/*; do               			\
-		   $(INSTALL) -c -m 755 $$i $(INSTDIR)/bin;             \
-		done                                                    \
+	@if test -f lib/libSAMRAI_tbox.so; then \
+	   for i in lib/libSAMRAI*.so; do \
+	      $(INSTALL) -p -c -m 644 $$i $(INSTDIR)/lib; \
+	   done \
+	fi
+	@if test -f bin/restart-redistribute; then \
+	   for i in bin/*; do \
+	      $(INSTALL) -p -c -m 755 $$i $(INSTDIR)/bin; \
+	   done \
 	fi
 
 # Rebuild config.status if configure changed.
@@ -191,6 +192,10 @@ dox redox devdox redevdox:
 check:
 	(cd source/test; $(MAKE) check)
 
+# Compile the testlib needed by the SAMRAI test suite
+testlib:
+	(cd source/test/testlib && $(MAKE) library) || exit 1
+
 # Compile the SAMRAI test suite
 checkcompile:
 	(cd source/test; $(MAKE) checkcompile)
@@ -199,23 +204,41 @@ checkcompile:
 checktest:
 	(cd source/test; $(MAKE) checktest)
 
+# Run the SAMRAI example problems
+examples:
+	(cd source/test; $(MAKE) examples)
+
+# Run the SAMRAI performance tests
+perf:
+	(cd source/test; $(MAKE) perf)
+
+# Compile the SAMRAI test suite
+# Run the SAMRAI test suite
+# Run the SAMRAI example problems
+# Run the SAMRAI performance tests
+everything:
+	(cd source/test; $(MAKE) checkcompile || exit 1)
+	(cd source/test; $(MAKE) checktest)
+	(cd source/test; $(MAKE) examples)
+	(cd source/test; $(MAKE) perf)
+
 memtest: 
-	rm -f ~/insure.out 
+	$(RM) ~/insure.out 
 	$(MAKE) checktest
-	@NUM_INSURE_RUNS=`grep "PROBLEM SUMMARY - by type" ~/insure.out| wc -l`;            \
-	NO_LEAKS=`grep "No leaks were found" ~/insure.out | wc -l`;                         \
-        NUM_INSURE_ERRORS=`grep TOTAL ~/insure.out | awk '{ sum += $$2}; END {print sum}'`; \
-	if test $$NO_LEAKS -ne $$NUM_INSURE_RUNS;                                           \
-	then                                                                                \
-	   echo "FAIL: Insure++ reported memory leaks";                                     \
-	else                                                                                \
-	   echo "PASSED: Insure++ reported no memory leaks";                                \
-	fi;                                                                                 \
-        if test "$$NUM_INSURE_ERRORS" -ne "0";                                              \
-	then                                                                                \
-	   echo "FAIL: Insure++ reported unexpected errors";                                \
-	else                                                                                \
-	   echo "PASSED: Insure++ reported no unexpected errors";                           \
+	@NUM_INSURE_RUNS=`grep "PROBLEM SUMMARY - by type" ~/insure.out| wc -l`; \
+	NO_LEAKS=`grep "No leaks were found" ~/insure.out | wc -l`; \
+	NUM_INSURE_ERRORS=`grep TOTAL ~/insure.out | awk '{ sum += $$2}; END {print sum}'`; \
+	if test $$NO_LEAKS -ne $$NUM_INSURE_RUNS; \
+	then \
+	   echo "FAIL: Insure++ reported memory leaks"; \
+	else \
+	   echo "PASSED: Insure++ reported no memory leaks"; \
+	fi; \
+        if test "$$NUM_INSURE_ERRORS" -ne "0"; \
+	then \
+	   echo "FAIL: Insure++ reported unexpected errors"; \
+	else \
+	   echo "PASSED: Insure++ reported no unexpected errors"; \
 	fi                                                                      
 
 # Update copies/links in the include directory
@@ -237,5 +260,5 @@ genfiles: update indent
 	@-(cd @top_srcdir@; \
 	for i in `find . -name genfiles.sh`; \
 	do \
-		(cd `dirname $$i` && ./genfiles.sh) \
+	   (cd `dirname $$i` && ./genfiles.sh) \
 	done)
diff --git a/base/SAMRAI/SAMRAI/source/test/FAC_adaptive/Makefile.in b/base/SAMRAI/SAMRAI/source/test/FAC_adaptive/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/FAC_adaptive/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/FAC_adaptive/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for the FAC test directory 
 ##
 #########################################################################
@@ -14,6 +14,9 @@ SUBDIR        = source/test/FAC_adaptive
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
+TESTLIBDIR    = $(OBJECT)/source/test/testlib
+TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
 
 default: check
 
@@ -21,14 +24,12 @@ include $(OBJECT)/config/Makefile.config
 
 CPPFLAGS_EXTRA= -DTESTING=1
 
-
 NUM_TESTS = 15
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o AdaptivePoisson.o \
-	get-input-filename.o \
-	printObject.o \
 	patchFcns.o \
 	setArrayData.o \
 	SinusoidFcn.o \
@@ -40,9 +41,13 @@ CXX_OBJS      = main.o AdaptivePoisson.o \
 	PoissonMultigaussianSolution.o \
 	PoissonPolynomialSolution.o
 
-main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND)
-	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS)	\
-	$(LIBSAMRAI3D) $(LIBSAMRAI) $(LDLIBS) -o main
+main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND) $(TESTLIB)
+	(cd $(TESTLIBDIR) && $(MAKE) library) || exit 1 
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(TESTLIB)	\
+	$(LIBSAMRAI) $(LDLIBS) -o main
+
+# Prevents "No rule to make target" error.  Built in the rule for main.
+$(TESTLIB):
 
 check:
 	$(MAKE) check2d
@@ -50,32 +55,49 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*.2d.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"FAC_adaptive\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
 	@for i in test_inputs/*.3d.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"FAC_adaptive\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
 examples:
 
-clean-check:
-	$(SAMCLEAN)
+perf:
 
-clean:
-	$(SAMCLEAN)
-	$(RM) *.f *main* 
-	$(RM) -rf *visit
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/LoadBalanceCorrectness/Makefile.in b/base/SAMRAI/SAMRAI/source/test/LoadBalanceCorrectness/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/LoadBalanceCorrectness/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/LoadBalanceCorrectness/Makefile.in
@@ -3,69 +3,96 @@
 ## This file is part of the SAMRAI distribution.  For full copyright
 ## information, see COPYRIGHT and COPYING.LESSER.
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   Test program for performance of load balancers.
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
-SRCDIR	      =	@srcdir@
+SAMRAI        = @top_srcdir@
+SRCDIR        = @srcdir@
 SUBDIR        = source/test/LoadBalanceCorrectness
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 OBJECT        = ../../..
-
-CPPFLAGS_EXTRA= -DNDIM=$(PDIM)  -DTESTING=1
+REPORT        = $(OBJECT)/report.xml
+TESTLIBDIR    = $(OBJECT)/source/test/testlib
+TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
 
 default: check
 
 include $(OBJECT)/config/Makefile.config
 
-NUM_TESTS = 8
+CPPFLAGS_EXTRA= -DTESTING=1
+
+NUM_TESTS = 34
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
-CXX_OBJS      = main-lbcorrectness.o DerivedVisOwnerData.o
+CXX_OBJS      = main-lbcorrectness.o
 
-INPUTS1D = rod.1d.input
-INPUTS2D = rect.2d.treelb.input rod.2d.treelb.input small_cube.2d.caplb.input small_cube.2d.treelb.input small_sphere.2d.caplb.input small_sphere.2d.treelb.input
-INPUTS3D = plank.3d.treelb.input small_cube.3d.treelb.input
+INPUTS2D = box.2d.tilecap.input box.2d.cascade.input box.2d.tilecascade.input lss.2d.cascade.input lss.2d.tilecascade.input box.2d.treelb.input box.2d.tilelb.input box.2d.graphlb.input box.2d.caplb.input lss.2d.caplb.input lss.2d.treelb.input lss.2d.tilelb.input lss.2d.graphlb.input front.2d.caplb.input front.2d.treelb.input front.2d.tilelb.input front.2d.graphlb.input
+INPUTS3D = box.3d.cascade.input box.3d.tilecascade.input lss.3d.cascade.input lss.3d.tilecascade.input box.3d.treelb.input box.3d.tilelb.input box.3d.graphlb.input box.3d.caplb.input lss.3d.caplb.input lss.3d.treelb.input lss.3d.tilelb.input lss.3d.graphlb.input front.3d.caplb.input front.3d.treelb.input front.3d.tilelb.input front.3d.graphlb.input int_overflow.3d.cascade.input
 
-main: $(CXX_OBJS) $(LIBSAMRAI)
-	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) \
+main:	$(CXX_OBJS) $(LIBSAMRAI) $(TESTLIB)
+	(cd $(TESTLIBDIR) && $(MAKE) library) || exit 1
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(TESTLIB) \
 	$(LIBSAMRAI) $(LDLIBS) -o $@
 
-check:
-		$(MAKE) check2d
-		$(MAKE) check3d
+testlib:
+	cd $(TESTLIBDIR) && $(MAKE) library
 
-check1d:	main
-		for f in $(INPUTS1D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "test_inputs/$$f";	\
-		done
+# Prevents "No rule to make target" error.  Built in the rule for main.
+$(TESTLIB):
+
+check:
+	$(MAKE) check2d
+	$(MAKE) check3d
 
 check2d:	main
-		for f in $(INPUTS2D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "test_inputs/$$f";	\
-		done
+	@for f in $(INPUTS2D); do	\
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"LoadBalanceCorrectness\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main "test_inputs/$$f" | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
-		for f in $(INPUTS3D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "test_inputs/$$f";	\
-		done
+	@for f in $(INPUTS3D); do	\
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"LoadBalanceCorrectness\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main "test_inputs/$$f" | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(OBJECT)/source/test/testtools/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(OBJECT)/source/test/testtools/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-		$(SAMCLEAN)
+examples:
 
-clean:
-		$(SAMCLEAN)
-		$(RM) *.f main
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/MblkEuler/Makefile.in b/base/SAMRAI/SAMRAI/source/test/MblkEuler/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/MblkEuler/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/MblkEuler/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for multiblock sample application 
 ##
 #########################################################################
@@ -14,58 +14,72 @@ SUBDIR        = source/test/MblkEuler
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
+TESTLIBDIR    = $(OBJECT)/source/test/testlib
+TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
 
 default:      check
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA= -DNDIM=$(PDIM)  -DTESTING=1
+CPPFLAGS_EXTRA= -DTESTING=1
 
 NUM_TESTS     = 1
 
 TEST_NPROCS   = @TEST_NPROCS@
+QUOTE = \"
 
-CXX_OBJS      = MblkGeometry.o main.o MblkEuler.o MblkHyperbolicLevelIntegrator.o \
-                MblkHyperbolicPatchStrategy.o Pointer-MblkHyperbolicLevelIntegrator.o
+CXX_OBJS      = MblkGeometry.o main.o MblkEuler.o
 
-F_OBJS      = upfluxsum.o boundaryconditions.o
+F_OBJS        = boundaryconditions.o
 
-main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
-	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS) \
+main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND) $(TESTLIB)
+	(cd $(TESTLIBDIR) && $(MAKE) library) || exit 1 
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS) $(TESTLIB) \
 	$(LIBSAMRAI) $(LDLIBS) -o $@
+
+# Prevents "No rule to make target" error.  Built in the rule for main.
+$(TESTLIB):
 
 check:
 	$(MAKE) check3d
 
 check3d:	main
 	@for i in test_inputs/*.3d.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
-
-examples3d: main
-	@for i in test_inputs/*.3d.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
-
-examples:
-	$(MAKE) examples3d	
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"MblkEuler\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-	$(SAMCLEAN)
+examples:
 
-clean: 
-	$(SAMCLEAN)
-	$(RM) *.f main viz*
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+	$(RM) viz*
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 redo: 
 	$(RM) main
@@ -74,7 +88,3 @@ include $(SRCDIR)/Makefile.depend
 
 boundaryconditions.o:	$(SRCDIR)/boundaryconditions.f $(SRCDIR)/bc_common.f
 	$(F77) $(FFLAGS) -c $(SRCDIR)/boundaryconditions.f -o $@
-
-upfluxsum.o:	$(SRCDIR)/upfluxsum.f
-	$(F77) $(FFLAGS) -c $(SRCDIR)/upfluxsum.f -o $@
-
diff --git a/base/SAMRAI/SAMRAI/source/test/MblkLinAdv/Makefile.in b/base/SAMRAI/SAMRAI/source/test/MblkLinAdv/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/MblkLinAdv/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/MblkLinAdv/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for linear advection sample application 
 ##
 #########################################################################
@@ -14,6 +14,9 @@ SUBDIR        = source/test/MblkLinAdv
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
+TESTLIBDIR    = $(OBJECT)/source/test/testlib
+TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
 
 default:      check
 
@@ -24,20 +27,18 @@ CPPFLAGS_EXTRA= -DTESTING=0
 NUM_TESTS     = 2
 
 TEST_NPROCS   = @TEST_NPROCS@
+QUOTE = \"
 
-CXX_OBJS      = MblkGeometry.o main.o MblkLinAdv.o MblkHyperbolicLevelIntegrator.o \
-	MblkHyperbolicPatchStrategy.o Pointer-MblkHyperbolicLevelIntegrator.o \
-	SkeletonCellDoubleConservativeLinearRefine.o Pointer-SkeletonCellDoubleConservativeLinearRefine.o \
-	SkeletonCellDoubleWeightedAverage.o Pointer-SkeletonCellDoubleWeightedAverage.o \
-	SkeletonOutersideDoubleWeightedAverage.o Pointer-SkeletonOutersideDoubleWeightedAverage.o \
-	SkeletonBoundaryUtilities2.o \
-	SkeletonBoundaryUtilities3.o
+CXX_OBJS      = MblkGeometry.o main.o MblkLinAdv.o \
+		SkeletonOutersideDoubleWeightedAverage.o 
 
-F_OBJS      = upfluxsum2d.o skelbdry2d.o upfluxsum3d.o skelbdry3d.o
-
-main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
-	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS) \
+main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND) $(TESTLIB)
+	(cd $(TESTLIBDIR) && $(MAKE) library) || exit 1 
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(TESTLIB) \
 	$(LIBSAMRAI) $(LDLIBS) -o $@
+
+# Prevents "No rule to make target" error.  Built in the rule for main.
+$(TESTLIB):
 
 check:
 	$(MAKE) check3d
@@ -46,59 +47,43 @@ check2d:
 
 check3d:       main
 	@for i in test_inputs/*.3d.input ; do \
-	 $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-	       ./main $${i}; \
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"MblkLinAdv\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
-
-examples2d: 
-
-examples3d: main
-	@for i in $(SRCDIR)/example_inputs/*.3d.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
 examples:
-	$(MAKE) examples2d
-	$(MAKE) examples3d
 
-clean-check:
-	$(SAMCLEAN)
+perf:
 
-clean: 
-	$(SAMCLEAN)
-	$(RM) *.f main viz*
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+	$(RM) viz*
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 redo: 
 	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
-
-FORTRAN       = $(SRCDIR)/fortran
-M4DIRS        = -DFORTDIR=$(FORTRAN) $(SAMRAI_M4_FLAGS)
-
-skelbdry2d.o:	$(FORTRAN)/2d/skelbdry2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/2d/skelbdry2d.m4 > skelbdry2d.f
-	$(F77) $(FFLAGS) -c skelbdry2d.f -o $@
-
-upfluxsum2d.o:	$(FORTRAN)/2d/upfluxsum2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/2d/upfluxsum2d.m4 > upfluxsum2d.f
-	$(F77) $(FFLAGS) -c upfluxsum2d.f -o $@
-
-
-skelbdry3d.o:	$(FORTRAN)/3d/skelbdry3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/3d/skelbdry3d.m4 > skelbdry3d.f
-	$(F77) $(FFLAGS) -c skelbdry3d.f -o $@
-
-upfluxsum3d.o:	$(FORTRAN)/3d/upfluxsum3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/3d/upfluxsum3d.m4 > upfluxsum3d.f
-	$(F77) $(FFLAGS) -c upfluxsum3d.f -o $@
 
diff --git a/base/SAMRAI/SAMRAI/source/test/applications/ConvDiff/Makefile.in b/base/SAMRAI/SAMRAI/source/test/applications/ConvDiff/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/applications/ConvDiff/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/applications/ConvDiff/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for Convection-Diffusion ODE sample application 
 ##
 #########################################################################
@@ -14,53 +14,97 @@ SUBDIR        = source/test/applications/ConvDiff
 VPATH         = @srcdir@
 TESTTOOLS     = ../../testtools
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
+TESTLIBDIR    = $(OBJECT)/source/test/testlib
+TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
 
 default: check	
 
 include $(OBJECT)/config/Makefile.config
 
-AUTOTEST      = $(SAMRAI)/source/test/applications
-CPPFLAGS_EXTRA= -I$(AUTOTEST) -DTESTING=1
+SUBDIRS = fortran
+
+CPPFLAGS_EXTRA = -DTESTING=1
 
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
-CXX_OBJS      = main.o ConvDiff.o MainRestartData.o AutoTester.o
-F77_OBJS      = compute_rhs2d.o init2d.o rkstep2d.o tag_cells2d.o \
-		compute_rhs3d.o init3d.o rkstep3d.o tag_cells3d.o
+CXX_OBJS      = main.o ConvDiff.o MainRestartData.o
+F77_OBJS      = fortran/compute_rhs2d.o \
+		fortran/init2d.o \
+		fortran/rkstep2d.o \
+		fortran/tag_cells2d.o \
+		fortran/compute_rhs3d.o \
+		fortran/init3d.o \
+		fortran/rkstep3d.o \
+		fortran/tag_cells3d.o
 
 
-main:	$(CXX_OBJS) $(F77_OBJS) $(LIBSAMRAIDEPEND)
-	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F77_OBJS)	\
+main:	$(CXX_OBJS) $(F77_OBJS) $(LIBSAMRAIDEPEND) $(TESTLIB)
+	(cd $(TESTLIBDIR) && $(MAKE) library) || exit 1
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F77_OBJS) $(TESTLIB) \
 	$(LIBSAMRAI3D) $(LIBSAMRAI) $(LDLIBS) -o main
+
+# Prevents "No rule to make target" error.  Built in the rule for main.
+$(TESTLIB):
+
+fortran/compute_rhs2d.o:
+
+fortran/init2d.o:
+
+fortran/rkstep2d.o:
+
+fortran/tag_cells2d.o:
+
+fortran/compute_rhs3d.o:
+
+fortran/init3d.o:
+
+fortran/rkstep3d.o:
+
+fortran/tag_cells3d.o:
 
 check:
 	$(MAKE) check2d
 	$(MAKE) check3d
 
 check2d:	main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.2d.input;
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications ConvDiff\" name=$(QUOTE)2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check3d:	main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.3d.input;
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications ConvDiff\" name=$(QUOTE)3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.3d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
 examples2d: main
-	@for i in $(SRCDIR)/example_inputs/*.2d.input ; do	\
+	@for i in example_inputs/*.2d.input ; do	\
 	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
 		./main $${i};	\
 	done
 
 examples3d: main
-	@for i in $(SRCDIR)/example_inputs/*.3d.input ; do	\
+	@for i in example_inputs/*.3d.input ; do	\
 	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
 		./main $${i};	\
 	done
@@ -69,12 +113,22 @@ examples:
 	$(MAKE) examples2d
 	$(MAKE) examples3d
 
-clean-check:
-	$(SAMCLEAN)
+perf:
 
-clean:		clean-check
-	$(RM) *.f main
-	$(RM) -rf test*restart
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+	$(RM) test*.restart
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 
 redo:
 	$(RM) core main*d
@@ -83,40 +137,4 @@ include $(SRCDIR)/Makefile.depend
 
 AutoTester.o:	$(AUTOTEST)/AutoTester.C
 	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $(AUTOTEST)/AutoTester.C -o $@
-
-FORTRAN		= $(SRCDIR)/fortran
-M4DIRS		= -DFORTDIR=$(FORTRAN) $(SAMRAI_M4_FLAGS)
-
-compute_rhs2d.o:	$(FORTRAN)/compute_rhs2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/compute_rhs2d.m4 > compute_rhs2d.f
-	$(F77) $(FFLAGS) -c compute_rhs2d.f -o $@
-
-init2d.o:		$(FORTRAN)/init2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/init2d.m4 > init2d.f
-	$(F77) $(FFLAGS) -c init2d.f -o $@
-
-tag_cells2d.o:	$(FORTRAN)/tag_cells2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/tag_cells2d.m4 > tag_cells2d.f
-	$(F77) $(FFLAGS) -c tag_cells2d.f -o $@
-
-rkstep2d.o:	$(FORTRAN)/rkstep2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/rkstep2d.m4 > rkstep2d.f
-	$(F77) $(FFLAGS) -c rkstep2d.f -o $@
-
-
-compute_rhs3d.o:	$(FORTRAN)/compute_rhs3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/compute_rhs3d.m4 > compute_rhs3d.f
-	$(F77) $(FFLAGS) -c compute_rhs3d.f -o $@
-
-init3d.o:		$(FORTRAN)/init3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/init3d.m4 > init3d.f
-	$(F77) $(FFLAGS) -c init3d.f -o $@
-
-tag_cells3d.o:	$(FORTRAN)/tag_cells3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/tag_cells3d.m4 > tag_cells3d.f
-	$(F77) $(FFLAGS) -c tag_cells3d.f -o $@
-
-rkstep3d.o:	$(FORTRAN)/rkstep3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/rkstep3d.m4 > rkstep3d.f
-	$(F77) $(FFLAGS) -c rkstep3d.f -o $@
 
diff --git a/base/SAMRAI/SAMRAI/source/test/applications/Euler/Makefile.in b/base/SAMRAI/SAMRAI/source/test/applications/Euler/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/applications/Euler/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/applications/Euler/Makefile.in
@@ -3,8 +3,8 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
-## Description:   makefile for Euler gas dynamics sample application 
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
+## Description:   makefile for Euler gas dynamics sample application
 ##
 #########################################################################
 
@@ -14,142 +14,213 @@ SUBDIR        = source/test/applications/Euler
 VPATH         = @srcdir@
 TESTTOOLS     = ../../testtools
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
+TESTLIBDIR    = $(OBJECT)/source/test/testlib
+TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
 
 default:        check
 
 include $(OBJECT)/config/Makefile.config
 
-AUTOTEST      = $(SAMRAI)/source/test/applications
-CPPFLAGS_EXTRA= -I$(AUTOTEST) -DNDIM=$(PDIM) -DTESTING=1
-FORTRAN       = $(SRCDIR)/fortran/$(PDIM)d
+SUBDIRS = fortran
+
+CPPFLAGS_EXTRA = -DTESTING=1
 
 NUM_TESTS = 12
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
-CXX_OBJS      = main.o Euler.o AutoTester.o
+CXX_OBJS      = main.o Euler.o
 F_OBJS      = \
-		avgint2d.o flaten1d2d.o flux2d.o grad2d.o init2d.o stable2d.o \
-		stufprobc.o trace2d.o trace1d2d.o \
-		avgint3d.o flaten1d3d.o flux3d.o grad3d.o init3d.o stable3d.o \
-		trace3d.o trace1d3d.o fluxcorner3d.o
+	fortran/avgint2d.o \
+	fortran/flaten1d2d.o \
+	fortran/flux2d.o \
+	fortran/grad2d.o \
+	fortran/init2d.o \
+	fortran/stable2d.o \
+	fortran/stufprobc.o \
+	fortran/trace2d.o \
+	fortran/trace1d2d.o \
+	fortran/avgint3d.o \
+	fortran/flaten1d3d.o \
+	fortran/flux3d.o \
+	fortran/grad3d.o \
+	fortran/init3d.o \
+	fortran/stable3d.o \
+	fortran/trace3d.o \
+	fortran/trace1d3d.o \
+	fortran/fluxcorner3d.o
 
-main:		$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
-		$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS)	\
-		$(LIBSAMRAI3D) $(LIBSAMRAI) $(LDLIBS) -o main
+main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND) $(TESTLIB)
+	(cd $(TESTLIBDIR) && $(MAKE) library) || exit 1
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS) $(TESTLIB)	\
+	$(LIBSAMRAI3D) $(LIBSAMRAI) $(LDLIBS) -o main
+
+# Prevents "No rule to make target" error.  Built in the rule for main.
+$(TESTLIB):
+
+fortran/avgint2d.o:
+
+fortran/flaten1d2d.o:
+
+fortran/flux2d.o:
+
+fortran/grad2d.o:
+
+fortran/init2d.o:
+
+fortran/stable2d.o:
+
+fortran/stufprobc.o:
+
+fortran/trace2d.o:
+
+fortran/trace1d2d.o:
+
+fortran/avgint3d.o:
+
+fortran/flaten1d3d.o:
+
+fortran/flux3d.o:
+
+fortran/grad3d.o:
+
+fortran/init3d.o:
+
+fortran/stable3d.o:
+
+fortran/trace3d.o:
+
+fortran/trace1d3d.o:
+
+fortran/fluxcorner3d.o:
 
 check:
-		$(MAKE) check2d
-		$(MAKE) check3d
+	$(MAKE) check2d
+	$(MAKE) check3d
 
 check2d:	main
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.2d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.2d.input test.2d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.2d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.2d.input test_sync.2d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_restart.2d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_restart.2d.input test_restart.2d.restart 5
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d restart $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.2d.input test.2d.restart 5 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d sync $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d sync restart $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.2d.input test_sync.2d.restart 5 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d restart $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_restart.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)2d restart restart $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_restart.2d.input test_restart.2d.restart 5 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check3d:	main
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.3d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test.3d.input test.3d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.3d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync.3d.input test_sync.3d.restart 5;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync_restart.3d.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/test_sync_restart.3d.input test_sync_restart.3d.restart 5
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.3d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d restart $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test.3d.input test.3d.restart 5 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d sync $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.3d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d sync restart $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync.3d.input test_sync.3d.restart 5 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d sync_restart $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync_restart.3d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"applications Euler\" name=$(QUOTE)3d sync_restart restart $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/test_sync_restart.3d.input test_sync_restart.3d.restart 5 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-		$(SAMCLEAN)
+examples2d:	main
+	@for i in example_inputs/*.2d.input ; do	\
+	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
+		./main $${i};	\
+	done
 
-clean:		clean-check
-		$(RM) *.f main
-		$(RM) -rf test*restart test*visit viz*
+examples3d:	main
+	@for i in example_inputs/*.3d.input ; do	\
+	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
+		./main $${i};	\
+	done
+
+examples:
+	$(MAKE) examples2d
+	$(MAKE) examples3d
+
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+	$(RM) test*restart viz*
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 
 include $(SRCDIR)/Makefile.depend
 
-FORTRAN       = $(SRCDIR)/fortran
-M4DIRS        = -DFORTDIR=$(FORTRAN) $(SAMRAI_M4_FLAGS)
-
 AutoTester.o:	$(AUTOTEST)/AutoTester.C
-		$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c  $(AUTOTEST)/AutoTester.C \
-		-o $@
-
-avgint2d.o:	$(FORTRAN)/avgint2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/avgint2d.m4 > avgint2d.f
-		$(F77) $(FFLAGS) -c avgint2d.f -o $@
-
-avgint3d.o:	$(FORTRAN)/avgint3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/avgint3d.m4 > avgint3d.f
-		$(F77) $(FFLAGS) -c avgint3d.f -o $@
-
-flaten1d2d.o:	$(FORTRAN)/flaten1d2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/flaten1d2d.m4 > flaten1d2d.f
-		$(F77) $(FFLAGS) -c flaten1d2d.f -o $@
-
-flaten1d3d.o:	$(FORTRAN)/flaten1d3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/flaten1d3d.m4 > flaten1d3d.f
-		$(F77) $(FFLAGS) -c flaten1d3d.f -o $@
-
-flux2d.o:		$(FORTRAN)/flux2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/flux2d.m4 > flux2d.f
-		$(F77) $(FFLAGS) -c flux2d.f -o $@
-
-flux3d.o:		$(FORTRAN)/flux3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/flux3d.m4 > flux3d.f
-		$(F77) $(FFLAGS) -c flux3d.f -o $@
-
-fluxcorner3d.o:	$(FORTRAN)/fluxcorner3d.m4
-		$(M4) -B8096 $(M4DIRS) $(FORTRAN)/fluxcorner3d.m4 > fluxcorner3d.f
-		$(F77) $(FFLAGS) -c fluxcorner3d.f -o $@
-
-grad2d.o:		$(FORTRAN)/grad2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/grad2d.m4 > grad2d.f
-		$(F77) $(FFLAGS) -c grad2d.f -o $@
-
-grad3d.o:		$(FORTRAN)/grad3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/grad3d.m4 > grad3d.f
-		$(F77) $(FFLAGS) -c grad3d.f -o $@
-
-init2d.o:		$(FORTRAN)/init2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/init2d.m4 > init2d.f
-		$(F77) $(FFLAGS) -c init2d.f -o $@
-
-init3d.o:		$(FORTRAN)/init3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/init3d.m4 > init3d.f
-		$(F77) $(FFLAGS) -c init3d.f -o $@
-
-stable2d.o:	$(FORTRAN)/stable2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/stable2d.m4 > stable2d.f
-		$(F77) $(FFLAGS) -c stable2d.f -o $@
-
-stable3d.o:	$(FORTRAN)/stable3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/stable3d.m4 > stable3d.f
-		$(F77) $(FFLAGS) -c stable3d.f -o $@
-
-stufprobc.o:	$(FORTRAN)/stufprobc.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/stufprobc.m4 > stufprobc.f
-		$(F77) $(FFLAGS) -c stufprobc.f -o $@
-
-trace2d.o:	$(FORTRAN)/trace2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/trace2d.m4 > trace2d.f
-		$(F77) $(FFLAGS) -c trace2d.f -o $@
-
-trace3d.o:	$(FORTRAN)/trace3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/trace3d.m4 > trace3d.f
-		$(F77) $(FFLAGS) -c trace3d.f -o $@
-
-trace1d2d.o:	$(FORTRAN)/trace1d2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/trace1d2d.m4 > trace1d2d.f
-		$(F77) $(FFLAGS) -c trace1d2d.f -o $@
-
-trace1d3d.o:	$(FORTRAN)/trace1d3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/trace1d3d.m4 > trace1d3d.f
-		$(F77) $(FFLAGS) -c trace1d3d.f -o $@
+	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c  $(AUTOTEST)/AutoTester.C -o $@
diff --git a/base/SAMRAI/SAMRAI/source/test/async_comm/Makefile.in b/base/SAMRAI/SAMRAI/source/test/async_comm/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/async_comm/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/async_comm/Makefile.in
@@ -3,17 +3,18 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for the asynchromous communication class tests 
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
-SRCDIR	      =	@srcdir@
+SAMRAI        = @top_srcdir@
+SRCDIR        = @srcdir@
 SUBDIR        = source/test/async_comm
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA =  -DTESTING=1
 
@@ -24,6 +25,7 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 main-async_comm: main-async_comm.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main-async_comm.o $(LIBSAMRAI) $(LDLIBS) -o $@
@@ -32,8 +34,19 @@ main-peer_comm: main-peer_comm.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main-peer_comm.o $(LIBSAMRAI) $(LDLIBS) -o $@
 
 check:		checkcompile
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main-async_comm test_inputs/async.default.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main-peer_comm test_inputs/peer.default.input
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"async_comm\" name=$(QUOTE)async $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main-async_comm test_inputs/async.default.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"async_comm\" name=$(QUOTE)peer $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main-peer_comm test_inputs/peer.default.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check2d:
 	$(MAKE) check
@@ -44,13 +57,26 @@ check3d:
 checkcompile: main-async_comm main-peer_comm
 
 checktest:      checkcompile
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean:
-	$(SAMCLEAN)
+examples:
+
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
 	$(RM) main-async_comm main-peer_comm
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/boundary/Makefile.in b/base/SAMRAI/SAMRAI/source/test/boundary/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/boundary/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/boundary/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for boundary utilities sample application 
 ##
 #########################################################################
@@ -14,17 +14,19 @@ SUBDIR        = source/test/boundary
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check	
 
 include $(OBJECT)/config/Makefile.config
 
 AUTOTEST      = $(SAMRAI)/source/test/boundary
-CPPFLAGS_EXTRA= -I$(AUTOTEST) -DNDIM=$(PDIM) -DTESTING=1
+CPPFLAGS_EXTRA= -I$(AUTOTEST) -DTESTING=1
 
 NUM_TESTS = 13
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o BoundaryDataTester.o
 
@@ -38,29 +40,49 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"boundary\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	   $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"boundary\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
+examples:
 
-clean-check:
-	$(SAMCLEAN)
+perf:
 
-clean:		clean-check
-	$(RM) *main* 
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/communication/Makefile.in b/base/SAMRAI/SAMRAI/source/test/communication/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/communication/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/communication/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for SAMRAI communication tests 
 ##
 #########################################################################
@@ -14,22 +14,25 @@ SUBDIR        = source/test/communication
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
+TESTLIBDIR    = $(OBJECT)/source/test/testlib
+TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
 
 default: check
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA= -DNDIM=$(PDIM)  -DTESTING=1
+CPPFLAGS_EXTRA= -DTESTING=1
 
 NUM_TESTS = 56
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = \
 	CommTester.o \
 	PatchDataTestStrategy.o \
 	main.o \
-	VisItDerivedData.o \
 	CellDataTest.o \
 	EdgeDataTest.o \
 	FaceDataTest.o \
@@ -37,12 +40,15 @@ CXX_OBJS      = \
 	OuterfaceDataTest.o \
 	OuternodeDataTest.o \
 	OutersideDataTest.o \
-	Pointer-CommTester.o \
 	SideDataTest.o
 
-main: $(CXX_OBJS) $(LIBSAMRAI)
-	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) \
+main:	$(CXX_OBJS) $(LIBSAMRAI) $(TESTLIB)
+	(cd $(TESTLIBDIR) && $(MAKE) library) || exit 1 
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(TESTLIB) \
 	$(LIBSAMRAI) $(LDLIBS) -o $@
+
+# Prevents "No rule to make target" error.  Built in the rule for main.
+$(TESTLIB):
 
 check:
 	$(MAKE) check2d
@@ -50,30 +56,50 @@ check:
 
 check2d: main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"communication\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d: main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"communication\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-	$(SAMCLEAN)
+examples:
 
-clean:		clean-check
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
 	$(RM) main
-	$(RM) -rf *visit
 
 include $(SRCDIR)/Makefile.depend
 
diff --git a/base/SAMRAI/SAMRAI/source/test/dataaccess/Makefile.in b/base/SAMRAI/SAMRAI/source/test/dataaccess/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/dataaccess/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/dataaccess/Makefile.in
@@ -3,17 +3,18 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for testing data access functionality 
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
-SRCDIR	      =	@srcdir@
+SAMRAI        = @top_srcdir@
+SRCDIR        = @srcdir@
 SUBDIR        = source/test/dataaccess
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
@@ -24,6 +25,7 @@ CPPFLAGS_EXTRA	= -DTESTING=1
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS	= main.o
 
@@ -32,33 +34,54 @@ main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND)
 	$(LIBSAMRAI) $(LDLIBS) -o $@
 
 check:
-		$(MAKE) check2d
-		$(MAKE) check3d
+	$(MAKE) check2d
+	$(MAKE) check3d
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"dataaccess\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"dataaccess\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-		$(SAMCLEAN)
+examples:
 
-clean:		clean-check
-		$(RM) *.f main
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean:	checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/dataops/Makefile.in b/base/SAMRAI/SAMRAI/source/test/dataops/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/dataops/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/dataops/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for testing patch data operations 
 ##
 #########################################################################
@@ -14,21 +14,29 @@ SUBDIR        = source/test/dataops
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check	
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA	= -DDISPLAY -DNDIM=$(PDIM)  -DTESTING=1
+CPPFLAGS_EXTRA	= -DDISPLAY -DTESTING=1
 
-ifneq (,$(findstring libdcomplex, "@SAMRAI_OPTIONAL_LIBS@ "))
-  NUM_TESTS = 17
+ifneq (,$(findstring libdcomplex, $(SAMRAI_LIBRARY_TARGETS)))
+  NUM_TESTS = 24
 else
-  NUM_TESTS = 11
+  NUM_TESTS = 14
 endif
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
+
+SampleIndexData.o:	$(SAMRAI)/source/test/dataops/SampleIndexData.C
+	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $(SAMRAI)/source/test/dataops/SampleIndexData.C -o $@
+
+indx_dataops:		indx_dataops.o  SampleIndexData.o $(LIBSAMRAIDEPEND) 
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) indx_dataops.o SampleIndexData.o $(LIBSAMRAI2D) $(LIBSAMRAI) $(LDLIBS) -o $@
 
 cell_patchtest:		cell_patchtest.o  $(LIBSAMRAIDEPEND) 
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) cell_patchtest.o $(LIBSAMRAI2D) $(LIBSAMRAI) $(LDLIBS) -o $@
@@ -72,7 +80,8 @@ TARGETS2D=	cell_patchtest \
 		face_hiertest \
 		node_hiertest \
 		side_hiertest \
-		edge_hiertest
+		edge_hiertest \
+		indx_dataops
 
 ifneq (,$(findstring complex, $(SAMRAI_LIBRARY_TARGETS)))
 TARGETS2D+=	cell_cplxtest \
@@ -87,14 +96,10 @@ checkcompile:   $(TARGETS2D) cell_hiertest
 
 check:
 	$(MAKE) check2d
-	$(MAKE) check3d
 
 check2d:	$(SAMRAI_LIBRARY_TARGETS)
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./cell_patchtest 2;
 
-check3d:	cell_patchtest cell_hiertest
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./cell_patchtest 3;
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./cell_hiertest 3;
+check3d:	$(SAMRAI_LIBRARY_TARGETS)
 
 libbool:
 
@@ -102,17 +107,76 @@ libchar:
 
 libfloat:
 
+# Note that tmp file names need to be distinct between targets
+# libdcomplex and libdefault to prevent race conditions using parallel
+# make.
+
 libdcomplex:	cell_cplxtest \
 		face_cplxtest \
 		node_cplxtest \
 		side_cplxtest \
 		edge_cplxtest
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./cell_cplxtest 2; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./cell_cplxtest 3; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./face_cplxtest 2; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./node_cplxtest 2; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./edge_cplxtest 2; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./side_cplxtest 2
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./cell_cplxtest 2 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./cell_cplxtest 3 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./face_cplxtest 2 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./face_cplxtest 3 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./node_cplxtest 2 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./node_cplxtest 3 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./edge_cplxtest 2 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./edge_cplxtest 3 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_cplxtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./side_cplxtest 2 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_cplxtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./side_cplxtest 3 | $(TEE) foo-cplx; \
+	  if ! grep "PASSED" foo-cplx >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo-cplx
 
 
 libdefault:	cell_patchtest \
@@ -120,27 +184,116 @@ libdefault:	cell_patchtest \
 		face_hiertest \
 		node_hiertest \
 		side_hiertest \
-		edge_hiertest
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./cell_hiertest 2; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./cell_hiertest 3; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./cell_patchtest 2; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./cell_patchtest 3; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./face_hiertest 2; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./node_hiertest 2; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./edge_hiertest 2; \
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./side_hiertest 2
+		edge_hiertest \
+		indx_dataops
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)indx_dataops 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./indx_dataops 2 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)indx_dataops 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./indx_dataops 3 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./cell_hiertest 2 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./cell_hiertest 3 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_patchtest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./cell_patchtest 2 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)cell_patchtest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./cell_patchtest 3 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./face_hiertest 2 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)face_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./face_hiertest 3 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./node_hiertest 2 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)node_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./node_hiertest 3 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./edge_hiertest 2 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)edge_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./edge_hiertest 3 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_hiertest 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./side_hiertest 2 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dataops\" name=$(QUOTE)side_hiertest 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./side_hiertest 3 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-		$(SAMCLEAN)
+examples:
 
-clean:		clean-check
-		$(RM) *_hiertest* *_cplxtest* *_patchtest*
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean:	checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) *_hiertest *_cplxtest *_patchtest *_dataops
 
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/dimension/Makefile.in b/base/SAMRAI/SAMRAI/source/test/dimension/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/dimension/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/dimension/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for timer and statistician main programs 
 ##
 #########################################################################
@@ -14,6 +14,7 @@ SUBDIR        = source/test/dimension
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
@@ -28,11 +29,18 @@ main:  main.o $(LIBSAMRAIDEPEND)
 NUM_TESTS = 1
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 checkcompile: main
 
 check:  checkcompile
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"dimension\" name=$(QUOTE)$$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check2d:
 	$(MAKE) check
@@ -41,15 +49,26 @@ check3d:
 	$(MAKE) check
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
+examples:
 
-clean:
-	$(SAMCLEAN)
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
 	$(RM) main
-	$(RM) -rf *.log.* stats
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/dlbg/Makefile.in b/base/SAMRAI/SAMRAI/source/test/dlbg/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/dlbg/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/dlbg/Makefile.in
@@ -3,34 +3,44 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for DLBG test 
 ##
 #########################################################################
 
-SAMRAI	      = @top_srcdir@
+SAMRAI        = @top_srcdir@
 SRCDIR        = @srcdir@
 SUBDIR        = source/test/dlbg
-VPATH         = @top_srcdir@/source/test/dlbg
+VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
+TESTLIBDIR    = $(OBJECT)/source/test/testlib
+TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
 
 default: check
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA= -DNDIM=$(PDIM) -DTESTING=1
+CPPFLAGS_EXTRA= -DTESTING=1
 
-CXX_OBJS      = main.o DLBGTest.o SinusoidalFrontTagger.o intToString.o get-input-filename.o
 NUM_TESTS = 3
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
-CXX_OBJS      = main.o DLBGTest.o SinusoidalFrontTagger.o get-input-filename.o
+CXX_OBJS      = main.o DLBGTest.o
 
-main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND)
-	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS)	\
+main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND) $(TESTLIB)
+	(cd $(TESTLIBDIR) && $(MAKE) library) || exit 1 
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(TESTLIB)	\
 	$(LIBSAMRAI) $(LDLIBS) -o $@
+
+testlib:
+	cd $(TESTLIBDIR) && $(MAKE) library
+
+# Prevents "No rule to make target" error.  Built in the rule for main.
+$(TESTLIB):
 
 check:
 	$(MAKE) check2d
@@ -38,30 +48,49 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"dlbg\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"dlbg\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-	$(SAMCLEAN)
+examples:
 
-clean:
-	$(SAMCLEAN)
-	$(RM) *.f *main*
-	$(RM) -rf restart-*d*
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/fill_pattern/Makefile.in b/base/SAMRAI/SAMRAI/source/test/fill_pattern/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/fill_pattern/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/fill_pattern/Makefile.in
@@ -3,17 +3,18 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for the fill_pattern tests 
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
+SAMRAI        =	@top_srcdir@
 SRCDIR	      =	@srcdir@
 SUBDIR        = source/test/fill_pattern
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA  = -DDISPLAY -DTESTING=1
 
@@ -24,6 +25,7 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 1
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS = main-fill-pattern.o
 
@@ -32,8 +34,14 @@ main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND)
 	$(LIBSAMRAI) $(LDLIBS) -o $@
 
 
-check:		main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main
+check:	main
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"fill_pattern\" name=$(QUOTE)$$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check2d:
 	$(MAKE) check
@@ -44,13 +52,26 @@ check3d:
 checkcompile: main
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean: 
-		$(SAMCLEAN)
-		$(RM) main
+examples:
+
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/hierarchy/Makefile.in b/base/SAMRAI/SAMRAI/source/test/hierarchy/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/hierarchy/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/hierarchy/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for SAMRAI patch hierarchy refine/coarsen tests 
 ##
 #########################################################################
@@ -14,19 +14,20 @@ SUBDIR        = source/test/hierarchy
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check	
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA= -DNDIM=$(PDIM)  -DTESTING=1
+CPPFLAGS_EXTRA= -DTESTING=1
 
-NUM_TESTS = 4
+NUM_TESTS = 6
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = HierarchyTester.o \
-		tbox_Pointer-HierarchyTester.o \
 		main.o
 
 main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND) 
@@ -35,15 +36,25 @@ main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND)
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"hierarchy\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"hierarchy\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check:
 	$(MAKE) check2d
@@ -52,15 +63,26 @@ check:
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-	$(SAMCLEAN)
+examples:
 
-clean:		clean-check
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
 	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/hypre/Makefile.in b/base/SAMRAI/SAMRAI/source/test/hypre/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/hypre/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/hypre/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for SAMRAI HYPRE interface test 
 ##
 #########################################################################
@@ -14,36 +14,33 @@ SUBDIR        = source/test/hypre
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA= -DNDIM=$(PDIM) -DTESTING=1
+SUBDIRS = fortran
+
+CPPFLAGS_EXTRA= -DTESTING=1
 
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o HyprePoisson.o
-F_OBJS      = hyprepoisson2d.o hyprepoisson3d.o
+F_OBJS      = fortran/hyprepoisson2d.o fortran/hyprepoisson3d.o
 
 main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS) \
 	$(LIBSAMRAI3D) $(LIBSAMRAI3D) $(LIBSAMRAI) $(LDLIBS) -o $@
 
-include $(SRCDIR)/Makefile.depend
+# Prevents "No rule to make target" error.  Built in the rule for main.
+fortran/hyprepoisson2d.o:
 
-FORTRAN         = $(SRCDIR)/fortran
-M4DIRS          = -DFORTDIR=$(FORTRAN) $(SAMRAI_M4_FLAGS)
-
-hyprepoisson2d.o:	$(FORTRAN)/hyprepoisson2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/hyprepoisson2d.m4 > hyprepoisson2d.f
-	$(F77) $(FFLAGS) -c hyprepoisson2d.f -o $@
-
-hyprepoisson3d.o:	$(FORTRAN)/hyprepoisson3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/hyprepoisson3d.m4 > hyprepoisson3d.f
-	$(F77) $(FFLAGS) -c hyprepoisson3d.f -o $@
+fortran/hyprepoisson3d.o:
 
 check:
 	$(MAKE) check2d
@@ -51,27 +48,51 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"hypre\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"hypre\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-	$(SAMCLEAN)
+examples:
 
-clean:		clean-check
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+	$(RM) *.out.*
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
 	$(RM) main
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 
+include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/inputdb/Makefile.in b/base/SAMRAI/SAMRAI/source/test/inputdb/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/inputdb/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/inputdb/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for testing the input database driver 
 ##
 #########################################################################
@@ -14,6 +14,7 @@ SUBDIR        = source/test/inputdb
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check	
 
@@ -22,32 +23,51 @@ include $(OBJECT)/config/Makefile.config
 CPPFLAGS_EXTRA= -DNDIM=2  -DTESTING=1
 
 main:	inputdb.o $(LIBSAMRAIDEPEND)
-		$(CXX) $(CXXFLAGS) $(LDFLAGS) inputdb.o $(LIBSAMRAI) $(LDLIBS) -o $@
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) inputdb.o $(LIBSAMRAI) $(LDLIBS) -o $@
 
 NUM_TESTS = 1
 
 TEST_NPROCS = @TEST_NPROCS@ 
+QUOTE = \"
 
 checkcompile: main
 
-check:		checkcompile
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-			./main inputdb.input
+check:	checkcompile
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"inputdb\" name=$(QUOTE)$$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/inputdb.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check2d:
-		$(MAKE) check
+	$(MAKE) check
 
 check3d:
-		$(MAKE) check
+	$(MAKE) check
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean:
-		$(SAMCLEAN)
-		$(RM) main
+examples:
+
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/logger/Makefile.in b/base/SAMRAI/SAMRAI/source/test/logger/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/logger/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/logger/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for timer and statistician test programs 
 ##
 #########################################################################
@@ -14,6 +14,7 @@ SUBDIR        = source/test/logger
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
@@ -32,24 +33,30 @@ userloggertest:  userloggertest.o $(LIBSAMRAIDEPEND)
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 check:  defaultloggertest userloggertest
 	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-                passed=1; \
-		$(OBJECT)/config/serpa-run $$p ./defaultloggertest; \
-		if ! grep "Test warning" defaultloggertest.log.0000000 >& /dev/null ; then passed=0; fi; \
-		if grep "Test debug1" defaultloggertest.log.0000000 >& /dev/null ; then passed=0; fi; \
-		if ! grep "Test debug2" defaultloggertest.log.0000000 >& /dev/null ; then passed=0; fi; \
-		if [ $$passed == 1 ] ; then echo "PASSED defaultloggertest"; else echo "FAILED defaultloggertest"; fi; \
+	  echo "    <testcase classname=\"logger\" name=$(QUOTE)defaultlogger $$p procs$(QUOTE)>" >> $(REPORT); \
+	  passed=1; \
+	  $(OBJECT)/config/serpa-run $$p ./defaultloggertest; \
+	  if ! grep "Test warning" defaultloggertest.log.0000000 >& /dev/null ; then passed=0; fi; \
+	  if grep "Test debug1" defaultloggertest.log.0000000 >& /dev/null ; then passed=0; fi; \
+	  if ! grep "Test debug2" defaultloggertest.log.0000000 >& /dev/null ; then passed=0; fi; \
+	  if [ $$passed == 1 ] ; then echo "PASSED defaultloggertest"; else echo "FAILED defaultloggertest"; fi; \
+	  if [ $$passed == 0 ] ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
 	done; \
 	for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
-                passed=1; \
-		$(OBJECT)/config/serpa-run $$p ./userloggertest; \
-		if ! grep "Test warning" user.log >& /dev/null ; then passed=0; fi; \
-		if grep "Test debug1" user.log >& /dev/null ; then passed=0; fi; \
-		if ! grep "Test debug2" user.log >& /dev/null ; then passed=0; fi; \
-		passed=1; \
-		if [ $$passed == 1 ] ; then echo "PASSED userloggertest"; else echo "FAILED userloggertest"; fi; \
+	  echo "    <testcase classname=\"logger\" name=$(QUOTE)userlogger $$p procs$(QUOTE)>" >> $(REPORT); \
+	  passed=1; \
+	  $(OBJECT)/config/serpa-run $$p ./userloggertest; \
+	  if ! grep "Test warning" user.log >& /dev/null ; then passed=0; fi; \
+	  if grep "Test debug1" user.log >& /dev/null ; then passed=0; fi; \
+	  if ! grep "Test debug2" user.log >& /dev/null ; then passed=0; fi; \
+	  if [ $$passed == 1 ] ; then echo "PASSED userloggertest"; else echo "FAILED userloggertest"; fi; \
+	  if [ $$passed == 0 ] ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
 	done;
 
 check2d:
@@ -61,14 +68,26 @@ check3d:
 checkcompile: userloggertest defaultloggertest
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean: 
-	$(SAMCLEAN)
-	$(RM) -rf defaultloggertest userloggertest
-	$(RM) -rf *.log.* stats
+examples:
+
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) defaultloggertest userloggertest
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/mblktree/Makefile.in b/base/SAMRAI/SAMRAI/source/test/mblktree/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/mblktree/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/mblktree/Makefile.in
@@ -3,17 +3,18 @@
 ## This file is part of the SAMRAI distribution.  For full copyright
 ## information, see COPYRIGHT and COPYING.LESSER.
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for the MultiblockMappedBoxTree tests
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
-SRCDIR	      =	@srcdir@
+SAMRAI        = @top_srcdir@
+SRCDIR        = @srcdir@
 SUBDIR        = source/test/mblktree
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA =  -DTESTING=1
 
@@ -29,35 +30,81 @@ TEST_NPROCS = 0
 else
 TEST_NPROCS = 1
 endif
+QUOTE = \"
 
 main:	main-mbtree.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main-mbtree.o $(LIBSAMRAI) $(LDLIBS) -o $@
 
 
-check:		main
+check:	main
 	$(MAKE) check2d
 	$(MAKE) check3d
 
 check2d:
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.3blk.simple.2d.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.3blk.subdivided.2d.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.5blk.simple.2d.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.5blk.subdivided.2d.input
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)3blks simple 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.3blk.simple.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)3blks subdivided 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.3blk.subdivided.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)5blks simple 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.5blk.simple.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)5blks subdivided 2d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.5blk.subdivided.2d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check3d:
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.full.simple.3d.input
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main test_inputs/mbtree.full.subdivided.3d.input
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)full simple 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.full.simple.3d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"mblktree\" name=$(QUOTE)full subdivided 3d $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/mbtree.full.subdivided.3d.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean:
-		$(SAMCLEAN)
-		$(RM) main
+examples:
+
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/nonlinear/Makefile.in b/base/SAMRAI/SAMRAI/source/test/nonlinear/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/nonlinear/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/nonlinear/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for nonlinear solver test 
 ##
 #########################################################################
@@ -14,244 +14,198 @@ SUBDIR        = source/test/nonlinear
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check	
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA= -DDISPLAY -DNDIM=$(PDIM)  -DTESTING=1
+SUBDIRS = fortran
 
-CXX_OBJS      = main.o ModifiedBratuProblem.o  \
-	tbox_Pointer-CellPoissonFACSolver-NDIM.o tbox_Pointer-ModifiedBratuProblem.o
-F_OBJS      =	\
-	FACjacobian1d.o bcFluxCopy1d.o bcFluxFix1d.o bratufunc1d.o \
-	err1d.o evalBratu1d.o evalDiffusionCoef1d.o evalExponential1d.o evalF1d.o \
-	evalFaceFluxes1d.o evalJv1d.o evalSource1d.o setbc1d.o adjcrsfineoffdiag1d.o \
-	\
-	FACjacobian3d.o bcFluxCopy3d.o bcFluxFix3d.o bratufunc3d.o \
-	err3d.o evalBratu3d.o evalDiffusionCoef3d.o evalExponential3d.o evalF3d.o \
-	evalFaceFluxes3d.o evalJv3d.o evalSource3d.o setbc3d.o \
-	\
-	FACjacobian2d.o bcFluxCopy2d.o bcFluxFix2d.o bratufunc2d.o \
-	err2d.o evalBratu2d.o evalDiffusionCoef2d.o evalExponential2d.o evalF2d.o \
-	evalFaceFluxes2d.o evalJv2d.o evalSource2d.o setbc2d.o
+CPPFLAGS_EXTRA= -DDISPLAY -DTESTING=1
 
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
+
+CXX_OBJS      = main.o ModifiedBratuProblem.o
+F_OBJS      =	\
+	fortran/FACjacobian1d.o \
+	fortran/bcFluxCopy1d.o \
+	fortran/bcFluxFix1d.o \
+	fortran/bratufunc1d.o \
+	fortran/err1d.o \
+	fortran/evalBratu1d.o \
+	fortran/evalDiffusionCoef1d.o \
+	fortran/evalExponential1d.o \
+	fortran/evalF1d.o \
+	fortran/evalFaceFluxes1d.o \
+	fortran/evalJv1d.o \
+	fortran/evalSource1d.o \
+	fortran/setbc1d.o \
+	fortran/adjcrsfineoffdiag1d.o \
+	fortran/FACjacobian3d.o \
+	fortran/bcFluxCopy3d.o \
+	fortran/bcFluxFix3d.o \
+	fortran/bratufunc3d.o \
+	fortran/err3d.o \
+	fortran/evalBratu3d.o \
+	fortran/evalDiffusionCoef3d.o \
+	fortran/evalExponential3d.o \
+	fortran/evalF3d.o \
+	fortran/evalFaceFluxes3d.o \
+	fortran/evalJv3d.o \
+	fortran/evalSource3d.o \
+	fortran/setbc3d.o \
+	fortran/FACjacobian2d.o \
+	fortran/bcFluxCopy2d.o \
+	fortran/bcFluxFix2d.o \
+	fortran/bratufunc2d.o \
+	fortran/err2d.o \
+	fortran/evalBratu2d.o \
+	fortran/evalDiffusionCoef2d.o \
+	fortran/evalExponential2d.o \
+	fortran/evalF2d.o \
+	fortran/evalFaceFluxes2d.o \
+	fortran/evalJv2d.o \
+	fortran/evalSource2d.o \
+	fortran/setbc2d.o
 
 main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS)	\
 	$(LIBSAMRAI) $(LDLIBS) -o main
 
+# Prevents "No rule to make target" error.  Built in the rule for main.
+fortran/FACjacobian1d.o:
+
+fortran/bcFluxCopy1d.o:
+
+fortran/bcFluxFix1d.o:
+
+fortran/bratufunc1d.o:
+
+fortran/err1d.o:
+
+fortran/evalBratu1d.o:
+
+fortran/evalDiffusionCoef1d.o:
+
+fortran/evalExponential1d.o:
+
+fortran/evalF1d.o:
+
+fortran/evalFaceFluxes1d.o:
+
+fortran/evalJv1d.o:
+
+fortran/evalSource1d.o:
+
+fortran/setbc1d.o:
+
+fortran/adjcrsfineoffdiag1d.o:
+
+fortran/FACjacobian3d.o:
+
+fortran/bcFluxCopy3d.o:
+
+fortran/bcFluxFix3d.o:
+
+fortran/bratufunc3d.o:
+
+fortran/err3d.o:
+
+fortran/evalBratu3d.o:
+
+fortran/evalDiffusionCoef3d.o:
+
+fortran/evalExponential3d.o:
+
+fortran/evalF3d.o:
+
+fortran/evalFaceFluxes3d.o:
+
+fortran/evalJv3d.o:
+
+fortran/evalSource3d.o:
+
+fortran/setbc3d.o:
+
+fortran/FACjacobian2d.o:
+
+fortran/bcFluxCopy2d.o:
+
+fortran/bcFluxFix2d.o:
+
+fortran/bratufunc2d.o:
+
+fortran/err2d.o:
+
+fortran/evalBratu2d.o:
+
+fortran/evalDiffusionCoef2d.o:
+
+fortran/evalExponential2d.o:
+
+fortran/evalF2d.o:
+
+fortran/evalFaceFluxes2d.o:
+
+fortran/evalJv2d.o:
+
+fortran/evalSource2d.o:
+
+fortran/setbc2d.o:
+
 check:
 	$(MAKE) check2d
-	echo Skipping for now: $(MAKE) check3d
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
-
-check3dx:	main
-	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
-
-# Disable check3d from test, because it takes too long.
-# It can be run using check3dx
-check3d:	main
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"nonlinear\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} -skip_petscrc | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-	$(SAMCLEAN)
+examples:
 
-clean:		clean-check
-	$(RM) *.o *.f main
-	$(RM) -rf *visit
+perf3d:	main
+	@for i in performance_inputs/*3d*.input ; do	\
+	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
+		./main $${i} -skip_petscrc;	\
+	done
+
+perf:
+	$(MAKE) perf3d
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+	$(RM) nkLog.32x32.8 *.timing*
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 
 include $(SRCDIR)/Makefile.depend
-
-FORTRAN       = $(SRCDIR)/fortran
-M4DIRS        = -DFORTDIR=$(FORTRAN) $(SAMRAI_M4_FLAGS)
-
-FACjacobian1d.o:	$(FORTRAN)/FACjacobian1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/FACjacobian1d.m4 > FACjacobian1d.f
-	$(F77) $(FFLAGS) -c FACjacobian1d.f -o $@
-
-adjcrsfineoffdiag1d.o:	$(FORTRAN)/adjcrsfineoffdiag1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/adjcrsfineoffdiag1d.m4 > adjcrsfineoffdiag1d.f
-	$(F77) $(FFLAGS) -c adjcrsfineoffdiag1d.f -o $@
-
-bcFluxCopy1d.o:	$(FORTRAN)/bcFluxCopy1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/bcFluxCopy1d.m4 > bcFluxCopy1d.f
-	$(F77) $(FFLAGS) -c bcFluxCopy1d.f -o $@
-
-bcFluxFix1d.o:	$(FORTRAN)/bcFluxFix1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/bcFluxFix1d.m4 > bcFluxFix1d.f
-	$(F77) $(FFLAGS) -c bcFluxFix1d.f -o $@
-
-bratufunc1d.o:	$(FORTRAN)/bratufunc1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/bratufunc1d.m4 > bratufunc1d.f
-	$(F77) $(FFLAGS) -c bratufunc1d.f -o $@
-
-err1d.o:	$(FORTRAN)/err1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/err1d.m4 > err1d.f
-	$(F77) $(FFLAGS) -c err1d.f -o $@
-
-evalBratu1d.o:	$(FORTRAN)/evalBratu1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalBratu1d.m4 > evalBratu1d.f
-	$(F77) $(FFLAGS) -c evalBratu1d.f -o $@
-
-evalDiffusionCoef1d.o:	$(FORTRAN)/evalDiffusionCoef1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalDiffusionCoef1d.m4 > evalDiffusionCoef1d.f
-	$(F77) $(FFLAGS) -c evalDiffusionCoef1d.f -o $@
-
-evalExponential1d.o:	$(FORTRAN)/evalExponential1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalExponential1d.m4 > evalExponential1d.f
-	$(F77) $(FFLAGS) -c evalExponential1d.f -o $@
-
-evalF1d.o:	$(FORTRAN)/evalF1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalF1d.m4 > evalF1d.f
-	$(F77) $(FFLAGS) -c evalF1d.f -o $@
-
-evalFaceFluxes1d.o:	$(FORTRAN)/evalFaceFluxes1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalFaceFluxes1d.m4 > evalFaceFluxes1d.f
-	$(F77) $(FFLAGS) -c evalFaceFluxes1d.f -o $@
-
-evalJv1d.o:	$(FORTRAN)/evalJv1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalJv1d.m4 > evalJv1d.f
-	$(F77) $(FFLAGS) -c evalJv1d.f -o $@
-
-evalSource1d.o:	$(FORTRAN)/evalSource1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalSource1d.m4 > evalSource1d.f
-	$(F77) $(FFLAGS) -c evalSource1d.f -o $@
-
-setbc1d.o:	$(FORTRAN)/setbc1d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/setbc1d.m4 > setbc1d.f
-	$(F77) $(FFLAGS) -c setbc1d.f -o $@
-
-
-FACjacobian2d.o:	$(FORTRAN)/FACjacobian2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/FACjacobian2d.m4 > FACjacobian2d.f
-	$(F77) $(FFLAGS) -c FACjacobian2d.f -o $@
-
-adjcrsfineoffdiag2d.o:	$(FORTRAN)/adjcrsfineoffdiag2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/adjcrsfineoffdiag2d.m4 > adjcrsfineoffdiag2d.f
-	$(F77) $(FFLAGS) -c adjcrsfineoffdiag2d.f -o $@
-
-bcFluxCopy2d.o:	$(FORTRAN)/bcFluxCopy2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/bcFluxCopy2d.m4 > bcFluxCopy2d.f
-	$(F77) $(FFLAGS) -c bcFluxCopy2d.f -o $@
-
-bcFluxFix2d.o:	$(FORTRAN)/bcFluxFix2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/bcFluxFix2d.m4 > bcFluxFix2d.f
-	$(F77) $(FFLAGS) -c bcFluxFix2d.f -o $@
-
-bratufunc2d.o:	$(FORTRAN)/bratufunc2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/bratufunc2d.m4 > bratufunc2d.f
-	$(F77) $(FFLAGS) -c bratufunc2d.f -o $@
-
-err2d.o:	$(FORTRAN)/err2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/err2d.m4 > err2d.f
-	$(F77) $(FFLAGS) -c err2d.f -o $@
-
-evalBratu2d.o:	$(FORTRAN)/evalBratu2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalBratu2d.m4 > evalBratu2d.f
-	$(F77) $(FFLAGS) -c evalBratu2d.f -o $@
-
-evalDiffusionCoef2d.o:	$(FORTRAN)/evalDiffusionCoef2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalDiffusionCoef2d.m4 > evalDiffusionCoef2d.f
-	$(F77) $(FFLAGS) -c evalDiffusionCoef2d.f -o $@
-
-evalExponential2d.o:	$(FORTRAN)/evalExponential2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalExponential2d.m4 > evalExponential2d.f
-	$(F77) $(FFLAGS) -c evalExponential2d.f -o $@
-
-evalF2d.o:	$(FORTRAN)/evalF2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalF2d.m4 > evalF2d.f
-	$(F77) $(FFLAGS) -c evalF2d.f -o $@
-
-evalFaceFluxes2d.o:	$(FORTRAN)/evalFaceFluxes2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalFaceFluxes2d.m4 > evalFaceFluxes2d.f
-	$(F77) $(FFLAGS) -c evalFaceFluxes2d.f -o $@
-
-evalJv2d.o:	$(FORTRAN)/evalJv2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalJv2d.m4 > evalJv2d.f
-	$(F77) $(FFLAGS) -c evalJv2d.f -o $@
-
-evalSource2d.o:	$(FORTRAN)/evalSource2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalSource2d.m4 > evalSource2d.f
-	$(F77) $(FFLAGS) -c evalSource2d.f -o $@
-
-setbc2d.o:	$(FORTRAN)/setbc2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/setbc2d.m4 > setbc2d.f
-	$(F77) $(FFLAGS) -c setbc2d.f -o $@
-
-
-FACjacobian3d.o:	$(FORTRAN)/FACjacobian3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/FACjacobian3d.m4 > FACjacobian3d.f
-	$(F77) $(FFLAGS) -c FACjacobian3d.f -o $@
-
-adjcrsfineoffdiag3d.o:	$(FORTRAN)/adjcrsfineoffdiag3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/adjcrsfineoffdiag3d.m4 > adjcrsfineoffdiag3d.f
-	$(F77) $(FFLAGS) -c adjcrsfineoffdiag3d.f -o $@
-
-bcFluxCopy3d.o:	$(FORTRAN)/bcFluxCopy3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/bcFluxCopy3d.m4 > bcFluxCopy3d.f
-	$(F77) $(FFLAGS) -c bcFluxCopy3d.f -o $@
-
-bcFluxFix3d.o:	$(FORTRAN)/bcFluxFix3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/bcFluxFix3d.m4 > bcFluxFix3d.f
-	$(F77) $(FFLAGS) -c bcFluxFix3d.f -o $@
-
-bratufunc3d.o:	$(FORTRAN)/bratufunc3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/bratufunc3d.m4 > bratufunc3d.f
-	$(F77) $(FFLAGS) -c bratufunc3d.f -o $@
-
-err3d.o:	$(FORTRAN)/err3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/err3d.m4 > err3d.f
-	$(F77) $(FFLAGS) -c err3d.f -o $@
-
-evalBratu3d.o:	$(FORTRAN)/evalBratu3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalBratu3d.m4 > evalBratu3d.f
-	$(F77) $(FFLAGS) -c evalBratu3d.f -o $@
-
-evalDiffusionCoef3d.o:	$(FORTRAN)/evalDiffusionCoef3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalDiffusionCoef3d.m4 > evalDiffusionCoef3d.f
-	$(F77) $(FFLAGS) -c evalDiffusionCoef3d.f -o $@
-
-evalExponential3d.o:	$(FORTRAN)/evalExponential3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalExponential3d.m4 > evalExponential3d.f
-	$(F77) $(FFLAGS) -c evalExponential3d.f -o $@
-
-evalF3d.o:	$(FORTRAN)/evalF3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalF3d.m4 > evalF3d.f
-	$(F77) $(FFLAGS) -c evalF3d.f -o $@
-
-evalFaceFluxes3d.o:	$(FORTRAN)/evalFaceFluxes3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalFaceFluxes3d.m4 > evalFaceFluxes3d.f
-	$(F77) $(FFLAGS) -c evalFaceFluxes3d.f -o $@
-
-evalJv3d.o:	$(FORTRAN)/evalJv3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalJv3d.m4 > evalJv3d.f
-	$(F77) $(FFLAGS) -c evalJv3d.f -o $@
-
-evalSource3d.o:	$(FORTRAN)/evalSource3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/evalSource3d.m4 > evalSource3d.f
-	$(F77) $(FFLAGS) -c evalSource3d.f -o $@
-
-setbc3d.o:	$(FORTRAN)/setbc3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/setbc3d.m4 > setbc3d.f
-	$(F77) $(FFLAGS) -c setbc3d.f -o $@
 
 
diff --git a/base/SAMRAI/SAMRAI/source/test/patchbdrysum/Makefile.in b/base/SAMRAI/SAMRAI/source/test/patchbdrysum/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/patchbdrysum/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/patchbdrysum/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for SAMRAI patch boundary hierarchy sum test 
 ##
 #########################################################################
@@ -14,23 +14,33 @@ SUBDIR        = source/test/patchbdrysum
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default:      check
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA= -DDISPLAY -DNDIM=$(PDIM) -DTESTING=1
+SUBDIRS = fortran
 
-CXX_OBJS      = main.o HierSumTest.o
-F_OBJS       = edgeops2d.o edgeops3d.o
+CPPFLAGS_EXTRA= -DDISPLAY -DTESTING=1
 
 NUM_TESTS = 17
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
+
+CXX_OBJS      = main.o HierSumTest.o
+F_OBJS       = fortran/edgeops2d.o fortran/edgeops3d.o
 
 main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS) \
 	$(LIBSAMRAI) $(LDLIBS) -o $@
+
+# Prevents "No rule to make target" error.  Built in the rule for main.
+fortran/edgeops2d.o:
+
+fortran/edgeops3d.o:
 
 check:
 	$(MAKE) check2d
@@ -39,43 +49,51 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"patchbdrysum\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"patchbdrysum\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest: checkcompile
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-	$(SAMCLEAN)
+examples:
 
-clean:
-	$(SAMCLEAN)
-	$(RM) *.f *main* 
-	$(RM) -rf restart-*d*
-	$(RM) -r viz*
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 
 
 include $(SRCDIR)/Makefile.depend
-
-FORTRAN       = $(SRCDIR)
-M4DIRS        = -DFORTDIR=$(FORTRAN) $(SAMRAI_M4_FLAGS)
-
-edgeops2d.o:	$(FORTRAN)/edgeops2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/edgeops2d.m4 > edgeops2d.f
-	$(F77) $(FFLAGS) -c edgeops2d.f -o $@
-
-edgeops3d.o:	$(FORTRAN)/edgeops3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/edgeops3d.m4 > edgeops3d.f
-	$(F77) $(FFLAGS) -c edgeops3d.f -o $@
diff --git a/base/SAMRAI/SAMRAI/source/test/performance/LinAdv/Makefile.in b/base/SAMRAI/SAMRAI/source/test/performance/LinAdv/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/performance/LinAdv/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/performance/LinAdv/Makefile.in
@@ -3,122 +3,127 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for linear advection performance test 
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
+SAMRAI        = @top_srcdir@
 SRCDIR        = @srcdir@
 SUBDIR        = source/test/performance/LinAdv
-VPATH         = @top_srcdir@/$(SUBDIR)
+VPATH         = @srcdir@
 OBJECT        = ../../../..
+REPORT        = $(OBJECT)/report.xml
+TESTLIBDIR    = $(OBJECT)/source/test/testlib
+TESTLIB       = $(TESTLIBDIR)/libSAMRAI_test$(LIB_SUFFIX)
 
 default:      main
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA= -DNDIM=$(PDIM)  -DTESTING=0
+SUBDIRS = fortran
+
+CPPFLAGS_EXTRA = 
 
 NUM_TESTS = 2
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
-CXX_OBJS      = main.o LinAdv.o SinusoidalFrontTagger.o
+CXX_OBJS      = main.o LinAdv.o
 F_OBJS      = \
-	    flux3d.o grad3d.o init3d.o stable3d.o stufprobc3d.o trace3d.o trace1d3d.o fluxcorner3d.o \
-	    flux2d.o grad2d.o init2d.o stable2d.o stufprobc2d.o trace2d.o trace1d2d.o
+	    fortran/flux3d.o fortran/grad3d.o fortran/init3d.o \
+	    fortran/stable3d.o fortran/stufprobc3d.o fortran/trace3d.o \
+	    fortran/trace1d3d.o fortran/fluxcorner3d.o \
+	    fortran/flux2d.o fortran/grad2d.o fortran/init2d.o \
+	    fortran/stable2d.o fortran/stufprobc2d.o fortran/trace2d.o \
+	    fortran/trace1d2d.o
 
-main:		$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
-		$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS)	\
-		$(LIBSAMRAI) $(LDLIBS) -o $@
+main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND) $(TESTLIB)
+	(cd $(TESTLIBDIR) && $(MAKE) library) || exit 1
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS) $(TESTLIB) \
+	$(LIBSAMRAI) $(LDLIBS) -o $@
 
-clean:
-		$(SAMCLEAN)
-		$(RM) *.f main
+# Prevents "No rule to make target" error.  Built in the rule for main.
+$(TESTLIB):
 
-check:
-#               $(MAKE) check2d
-		$(MAKE) check3d
+fortran/flux3d.o:
 
-check2d:	main
+fortran/grad3d.o:
 
-check3d:	main
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-			./main performance_inputs/domainexpansion.input;
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-			./main performance_inputs/domainexpansionb.input;
+fortran/init3d.o:
+
+fortran/stable3d.o:
+
+fortran/stufprobc3d.o:
+
+fortran/trace3d.o:
+
+fortran/trace1d3d.o:
+
+fortran/fluxcorner3d.o:
+
+fortran/flux2d.o:
+
+fortran/grad2d.o:
+
+fortran/init2d.o:
+
+fortran/stable2d.o:
+
+fortran/stufprobc2d.o:
+
+fortran/trace2d.o:
+
+fortran/trace1d2d.o:
+
+testlib:
+	cd $(TESTLIBDIR) && $(MAKE) library
+
+check:	main
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"performance LinAdv\" name=$(QUOTE)domainexpansion $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/domainexpansion.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"performance LinAdv\" name=$(QUOTE)domainexpansionb $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main test_inputs/domainexpansionb.input | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(OBJECT)/source/test/testtools/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(OBJECT)/source/test/testtools/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
+
+examples:
+
+perf:	main
+	@for i in performance_inputs/*.input ; do	\
+	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
+		./main $${i};	\
+	done
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+	$(RM) *.timing*
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 
 include $(SRCDIR)/Makefile.depend
-
-FORTRAN       = @srcdir@/fortran
-M4DIRS        = -DFORTDIR=$(FORTRAN) $(SAMRAI_M4_FLAGS)
-
-flux2d.o:		$(FORTRAN)/2d/flux2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/2d/flux2d.m4 > flux2d.f
-		$(F77) $(FFLAGS) -c flux2d.f -o $@
-
-grad2d.o:		$(FORTRAN)/2d/grad2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/2d/grad2d.m4 > grad2d.f
-		$(F77) $(FFLAGS) -c grad2d.f -o $@
-
-init2d.o:		$(FORTRAN)/2d/init2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/2d/init2d.m4 > init2d.f
-		$(F77) $(FFLAGS) -c init2d.f -o $@
-
-stable2d.o:	$(FORTRAN)/2d/stable2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/2d/stable2d.m4 > stable2d.f
-		$(F77) $(FFLAGS) -c stable2d.f -o $@
-
-stufprobc2d.o:	$(FORTRAN)/2d/stufprobc2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/2d/stufprobc2d.m4 > stufprobc2d.f
-		$(F77) $(FFLAGS) -c stufprobc2d.f -o $@
-
-trace2d.o:	$(FORTRAN)/2d/trace2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/2d/trace2d.m4 > trace2d.f
-		$(F77) $(FFLAGS) -c trace2d.f -o $@
-
-trace1d2d.o:	$(FORTRAN)/2d/trace1d2d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/2d/trace1d2d.m4 > trace1d2d.f
-		$(F77) $(FFLAGS) -c trace1d2d.f -o $@
-
-
-
-flux3d.o:		$(FORTRAN)/3d/flux3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/3d/flux3d.m4 > flux3d.f
-		$(F77) $(FFLAGS) -c flux3d.f -o $@
-
-fluxcorner3d.o:	$(FORTRAN)/3d/fluxcorner3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/3d/fluxcorner3d.m4 > fluxcorner3d.f
-		$(F77) $(FFLAGS) -c fluxcorner3d.f -o $@
-
-grad3d.o:		$(FORTRAN)/3d/grad3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/3d/grad3d.m4 > grad3d.f
-		$(F77) $(FFLAGS) -c grad3d.f -o $@
-
-init3d.o:		$(FORTRAN)/3d/init3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/3d/init3d.m4 > init3d.f
-		$(F77) $(FFLAGS) -c init3d.f -o $@
-
-stable3d.o:	$(FORTRAN)/3d/stable3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/3d/stable3d.m4 > stable3d.f
-		$(F77) $(FFLAGS) -c stable3d.f -o $@
-
-stufprobc3d.o:	$(FORTRAN)/3d/stufprobc3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/3d/stufprobc3d.m4 > stufprobc3d.f
-		$(F77) $(FFLAGS) -c stufprobc3d.f -o $@
-
-trace3d.o:	$(FORTRAN)/3d/trace3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/3d/trace3d.m4 > trace3d.f
-		$(F77) $(FFLAGS) -c trace3d.f -o $@
-
-trace1d3d.o:	$(FORTRAN)/3d/trace1d3d.m4
-		$(M4) $(M4DIRS) $(FORTRAN)/3d/trace1d3d.m4 > trace1d3d.f
-		$(F77) $(FFLAGS) -c trace1d3d.f -o $@
diff --git a/base/SAMRAI/SAMRAI/source/test/rank_group/Makefile.in b/base/SAMRAI/SAMRAI/source/test/rank_group/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/rank_group/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/rank_group/Makefile.in
@@ -3,18 +3,19 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   Test program for performance of load balancers. 
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
-SRCDIR	      =	@srcdir@
+SAMRAI        = @top_srcdir@
+SRCDIR        = @srcdir@
 SUBDIR        = source/test/rank_group
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
-CPPFLAGS_EXTRA= -DNDIM=$(PDIM)  -DTESTING=1
+CPPFLAGS_EXTRA= -DTESTING=1
 
 default: check
 
@@ -23,49 +24,66 @@ include $(OBJECT)/config/Makefile.config
 NUM_TESTS = 6
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 CXX_OBJS      = main.o
 
-INPUTS1D = rod.1d.input
 INPUTS2D = rect.2d.treelb.input rod.2d.treelb.input small_cube.2d.treelb.input  small_sphere.2d.treelb.input
 INPUTS3D = plank.3d.treelb.input small_cube.3d.treelb.input
 
-main: $(CXX_OBJS) $(LIBSAMRAI)
+main:	$(CXX_OBJS) $(LIBSAMRAI)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) \
 	$(LIBSAMRAI) $(LDLIBS) -o $@
 
 check:
-		$(MAKE) check2d
-		$(MAKE) check3d
-
-check1d:	main
-		for f in $(INPUTS1D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "test_inputs/$$f";	\
-		done
+	$(MAKE) check2d
+	$(MAKE) check3d
 
 check2d:	main
-		for f in $(INPUTS2D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "test_inputs/$$f";	\
-		done
+	@for f in $(INPUTS2D); do	\
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"rank_group\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main "test_inputs/$$f" | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
-		for f in $(INPUTS3D); do	\
-			$(OBJECT)/config/serpa-run $(TEST_NPROCS) \ ./main "test_inputs/$$f";	\
-		done
+	@for f in $(INPUTS3D); do	\
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"rank_group\" name=$(QUOTE)$$f $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main "test_inputs/$$f" | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 checkcompile: main
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(OBJECT)/source/test/testtools/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(OBJECT)/source/test/testtools/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-		$(SAMCLEAN)
+examples:
 
-clean:
-		$(SAMCLEAN)
-		$(RM) *.f main *visit
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/restartdb/Makefile.in b/base/SAMRAI/SAMRAI/source/test/restartdb/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/restartdb/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/restartdb/Makefile.in
@@ -3,27 +3,29 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for the restart database and HDF5 tests 
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
-SRCDIR	      =	@srcdir@
+SAMRAI        = @top_srcdir@
+SRCDIR        = @srcdir@
 SUBDIR        = source/test/restartdb
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA =  -DTESTING=1
 
-default: check	
+default: check
 
 include $(OBJECT)/config/Makefile.config
 
 NUM_TESTS = 5
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 testHDF5: mainHDF5.o database_tests.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) mainHDF5.o database_tests.o \
@@ -46,11 +48,37 @@ testMemory: mainMemory.o database_tests.o $(LIBSAMRAIDEPEND)
 	$(LIBSAMRAI) $(LDLIBS) -o testMemory
 
 check:	testHDF5 testHDF5AppFileOpen testSilo testSiloAppFileOpen testMemory
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./testHDF5
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./testHDF5AppFileOpen
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./testSilo
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./testSiloAppFileOpen
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./testMemory
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"restartdb\" name=$(QUOTE)HDF5 $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./testHDF5 | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"restartdb\" name=$(QUOTE)HDF5AppFilOpen $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./testHDF5AppFileOpen | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"restartdb\" name=$(QUOTE)Silo $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./testSilo | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"restartdb\" name=$(QUOTE)SiloAppFileOpen $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./testSiloAppFileOpen | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"restartdb\" name=$(QUOTE)Memory $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./testMemory | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check2d:
 	$(MAKE) check
@@ -62,14 +90,28 @@ checkcompile: testHDF5 testHDF5AppFileOpen testSilo testSiloAppFileOpen \
 	testMemory
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean:
-	$(SAMCLEAN)
-	$(RM) testHDF5 testSilo
-	$(RM) -r test_dir *.silo *.hdf5
+examples:
+
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+	$(RM) test_dir *.silo *.hdf5
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) testHDF5 testHDF5AppFileOpen testSilo testSiloAppFileOpen \
+	testMemory
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/samrai_mpi/Makefile.in b/base/SAMRAI/SAMRAI/source/test/samrai_mpi/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/samrai_mpi/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/samrai_mpi/Makefile.in
@@ -3,17 +3,18 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for the SAMRAI_MPI communication class tests 
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
-SRCDIR	      =	@srcdir@
+SAMRAI        = @top_srcdir@
+SRCDIR        = @srcdir@
 SUBDIR        = source/test/samrai_mpi
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 CPPFLAGS_EXTRA =  -DTESTING=1
 
@@ -27,6 +28,7 @@ TEST_NPROCS = @TEST_NPROCS@
 ifeq ($(findstring 2, ${TEST_NPROCS}),2)
 TEST_NPROCS = 1
 endif
+QUOTE = \"
 
 CXX_OBJS = mpi-interface-tests.o
 
@@ -43,9 +45,25 @@ main-runtime-disabled:	main-runtime-disabled.o $(CXX_OBJS) $(LIBSAMRAIDEPEND)
 	$(LIBSAMRAI) $(LDLIBS) -o $@
 
 check:		checkcompile
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main-runtime-on
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main-runtime-off
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main-runtime-disabled
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"samrai_mpi\" name=$(QUOTE)runtime-on $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main-runtime-on | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"samrai_mpi\" name=$(QUOTE)runtime-off $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main-runtime-off | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"samrai_mpi\" name=$(QUOTE)runtime-disabled $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main-runtime-disabled | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check2d:
 	$(MAKE) check
@@ -56,13 +74,26 @@ check3d:
 checkcompile: main-runtime-on main-runtime-off main-runtime-disabled
 
 checktest:      checkcompile
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean:
-	$(SAMCLEAN)
+examples:
+
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
 	$(RM) main-runtime-on main-runtime-off main-runtime-disabled
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/sparsedata/Makefile.in b/base/SAMRAI/SAMRAI/source/test/sparsedata/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/sparsedata/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/sparsedata/Makefile.in
@@ -3,17 +3,18 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for test of index data 
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
-SRCDIR	      =	@srcdir@
+SAMRAI        = @top_srcdir@
+SRCDIR        = @srcdir@
 SUBDIR        = source/test/sparsedata
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 #
 # For these classes don't turn off implicit template instantiation.
@@ -29,6 +30,7 @@ CPPFLAGS_EXTRA= -DTESTING=1
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 main: main.o SparseDataTester.o $(LIBSAMRAIDEPEND)
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) main.o SparseDataTester.o $(LIBSAMRAI2D) $(LIBSAMRAI) $(LDLIBS) -o $@
@@ -39,22 +41,46 @@ sparse: sparse_dataops.o $(LIBSAMRAIDEPEND)
 checkcompile: main sparse
 
 check:
-		$(MAKE) check2d
+	$(MAKE) check2d
 
 check2d:	main sparse
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main
-	$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./sparse
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"sparsedata\" name=$(QUOTE)main $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"sparsedata\" name=$(QUOTE)sparse $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./sparse | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check3d:
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean: 
-	$(SAMCLEAN)
-	@$(RM) *.f main* sparse*
+examples:
+
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	@$(RM) main sparse
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/sundials/Makefile.in b/base/SAMRAI/SAMRAI/source/test/sundials/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/sundials/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/sundials/Makefile.in
@@ -3,7 +3,7 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for cvode sample application 
 ##
 #########################################################################
@@ -14,25 +14,33 @@ SUBDIR        = source/test/sundials
 VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA= -DDISPLAY -DNDIM=$(PDIM) -DTESTING=1
+SUBDIRS = fortran
 
-CXX_OBJS      = main.o CVODEModel.o tbox_Pointer-CVODEModel.o
-F_OBJS        = FACjacobian2d.o FACjacobian3d.o 
+CPPFLAGS_EXTRA= -DDISPLAY -DTESTING=1
 
 NUM_TESTS = 4
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
+
+CXX_OBJS      = main.o CVODEModel.o
+F_OBJS        = fortran/FACjacobian2d.o fortran/FACjacobian3d.o 
 
 main:	$(CXX_OBJS) $(F_OBJS) $(LIBSAMRAIDEPEND)
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(CXX_OBJS) $(F_OBJS) \
 	$(LIBSAMRAI3D) $(LIBSAMRAI) $(LDLIBS) -o main
 
-checkcompile:   main
+# Prevents "No rule to make target" error.  Built in the rule for main.
+fortran/FACjacobian2d.o:
+
+fortran/FACjacobian3d.o:
 
 check:
 	$(MAKE) check2d
@@ -40,40 +48,52 @@ check:
 
 check2d:	main
 	@for i in test_inputs/*2d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"sundials\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
 
 check3d:	main
 	@for i in test_inputs/*3d*.input ; do	\
-	  $(OBJECT)/config/serpa-run $(TEST_NPROCS) \
-		./main $${i};	\
-	done
+	  for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	    echo "    <testcase classname=\"sundials\" name=$(QUOTE)$$i $$p procs$(QUOTE)>" >> $(REPORT); \
+	    $(OBJECT)/config/serpa-run $$p ./main $${i} | $(TEE) foo; \
+	    if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	    echo "    </testcase>" >> $(REPORT); \
+	  done \
+	done; \
+	$(RM) foo
+
+checkcompile:   main
 
 checktest:
-	rm -f makecheck.logfile
+	$(RM) makecheck.logfile
 	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-	rm -f makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
+examples:
 
-clean-check:
-	$(SAMCLEAN)
+perf:
 
-clean:
-	$(RM) *.o main
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
+	for DIR in $(SUBDIRS); do if test -d $$DIR; then (cd $$DIR && $(MAKE) $@) ; fi || exit 1; done
 
 include $(SRCDIR)/Makefile.depend
-
-FORTRAN       = $(SRCDIR)
-M4DIRS        = -DFORTDIR=$(FORTRAN) $(SAMRAI_M4_FLAGS)
-
-FACjacobian2d.o:	$(FORTRAN)/FACjacobian2d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/FACjacobian2d.m4 > FACjacobian2d.f
-	$(F77) $(FFLAGS) -c FACjacobian2d.f -o $@
-
-FACjacobian3d.o:	$(FORTRAN)/FACjacobian3d.m4
-	$(M4) $(M4DIRS) $(FORTRAN)/FACjacobian3d.m4 > FACjacobian3d.f
-	$(F77) $(FFLAGS) -c FACjacobian3d.f -o $@
 
 
diff --git a/base/SAMRAI/SAMRAI/source/test/variables/Makefile.in b/base/SAMRAI/SAMRAI/source/test/variables/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/variables/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/variables/Makefile.in
@@ -3,23 +3,24 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for testing variable database operations 
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
-SRCDIR	      =	@srcdir@
+SAMRAI        = @top_srcdir@
+SRCDIR        = @srcdir@
 SUBDIR        = source/test/variables
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
 include $(OBJECT)/config/Makefile.config
 
-CPPFLAGS_EXTRA	= -DNDIM=$(PDIM) -DTESTING=1
+CPPFLAGS_EXTRA	= -DTESTING=1
 
 CXX_OBJS	= main-var_db.o
 
@@ -30,28 +31,46 @@ main:	$(CXX_OBJS) $(LIBSAMRAIDEPEND)
 NUM_TESTS  = 1
 
 TEST_NPROCS = @TEST_NPROCS@
+QUOTE = \"
 
 checkcompile: main
 
 check:
-		$(MAKE) check2d
-		$(MAKE) check3d
+	$(MAKE) check2d
+	$(MAKE) check3d
 
 check2d:	checkcompile
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./main
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"variables\" name=$(QUOTE)$$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./main | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 check3d:
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
-clean-check:
-		$(SAMCLEAN)
+examples:
 
-clean:		clean-check
-		$(RM) *.f main*
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean:	checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) main
 
 include $(SRCDIR)/Makefile.depend
diff --git a/base/SAMRAI/SAMRAI/source/test/vector/Makefile.in b/base/SAMRAI/SAMRAI/source/test/vector/Makefile.in
--- a/base/SAMRAI/SAMRAI/source/test/vector/Makefile.in
+++ b/base/SAMRAI/SAMRAI/source/test/vector/Makefile.in
@@ -3,17 +3,18 @@
 ## This file is part of the SAMRAI distribution.  For full copyright 
 ## information, see COPYRIGHT and COPYING.LESSER. 
 ##
-## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
+## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
 ## Description:   makefile for test of patch data and vector operations 
 ##
 #########################################################################
 
-SAMRAI	      =	@top_srcdir@
-SRCDIR	      =	@srcdir@
+SAMRAI        = @top_srcdir@
+SRCDIR        = @srcdir@
 SUBDIR        = source/test/vector
-VPATH	      =	@srcdir@
+VPATH         = @srcdir@
 TESTTOOLS     = ../testtools
 OBJECT        = ../../..
+REPORT        = $(OBJECT)/report.xml
 
 default: check
 
@@ -21,38 +22,65 @@ include $(OBJECT)/config/Makefile.config
 
 CPPFLAGS_EXTRA= -DTESTING=1
 
-pvtest:		pvtest.o $(FOBJS) $(LIBSAMRAIDEPEND)
-		$(CXX) $(CXXFLAGS) $(LDFLAGS) pvtest.o $(COBJS) \
-			$(LIBSAMRAI3D) $(LIBSAMRAI) $(LDLIBS) -o $@
-kvtest:		kvtest.o $(FOBJS) $(LIBSAMRAIDEPEND)
-		$(CXX) $(CXXFLAGS) $(LDFLAGS) kvtest.o \
-			$(LIBSAMRAI3D) $(LIBSAMRAI) $(LDLIBS) -o $@
+pvtest:	pvtest.o $(FOBJS) $(LIBSAMRAIDEPEND)
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) pvtest.o $(COBJS) \
+		$(LIBSAMRAI3D) $(LIBSAMRAI) $(LDLIBS) -o $@
+kvtest:	kvtest.o $(FOBJS) $(LIBSAMRAIDEPEND)
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) kvtest.o \
+		$(LIBSAMRAI3D) $(LIBSAMRAI) $(LDLIBS) -o $@
 
 NUM_TESTS = 2
 
 TEST_NPROCS = @TEST_NPROCS@
+ifeq ($(findstring 4, ${TEST_NPROCS}),4)
+TEST_NPROCS = 1,2
+endif
+QUOTE = \"
 
 check:
-		$(MAKE) check2d
-		$(MAKE) check3d
+	$(MAKE) check2d
+	$(MAKE) check3d
 
 check2d:
 
 check3d:	kvtest pvtest
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./kvtest
-		$(OBJECT)/config/serpa-run $(TEST_NPROCS) ./pvtest
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"vector\" name=$(QUOTE)kvtest $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./kvtest | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done
+	@for p in `echo "$(TEST_NPROCS)" | tr "," " "`; do \
+	  echo "    <testcase classname=\"vector\" name=$(QUOTE)pvtest $$p procs$(QUOTE)>" >> $(REPORT); \
+	  $(OBJECT)/config/serpa-run $$p ./pvtest -skip_petscrc | $(TEE) foo; \
+	  if ! grep "PASSED" foo >& /dev/null ; then echo "      <failure/>" >> $(REPORT); fi; \
+	  echo "    </testcase>" >> $(REPORT); \
+	done; \
+	$(RM) foo
 
 checkcompile: kvtest pvtest
 
 checktest:
-		rm -f makecheck.logfile
-		$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
-		$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) makecheck.logfile
-		rm -f makecheck.logfile
+	$(RM) makecheck.logfile
+	$(MAKE) check 2>&1 | $(TEE) makecheck.logfile
+	$(TESTTOOLS)/testcount.sh $(TEST_NPROCS) $(NUM_TESTS) 0 makecheck.logfile
+	$(RM) makecheck.logfile
 
+examples:
 
-clean: 
-	$(SAMCLEAN)
-	$(RM) *.f *vtest*
+perf:
+
+everything:
+	$(MAKE) checkcompile || exit 1
+	$(MAKE) checktest
+	$(MAKE) examples
+	$(MAKE) perf
+
+checkclean:
+	$(CLEAN_COMMON_CHECK_FILES)
+
+clean: checkclean
+	$(CLEAN_COMMON_TEST_FILES)
+	$(RM) *vtest*
 
 include $(SRCDIR)/Makefile.depend
